#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not support $FUNCNAME, you may need to change this to bash, ksh, or zsh.
#
#   (2) Runs the script from the dir where build.gradle, settings.gradle are located.
#
#   Instead of using the default java -version output, this wrapper detects the Java
#   version from JAVA_HOME and falls back to java from the PATH.
#
#   As an added convenience, when this script is the current directory, you can just
#   type "gradlew" and the script will be executed.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}
    [ -L "$app_path" ]
do
    app_path=$(expr "$app_path" : '.\(.*\)' | sed 's#^/##')
    [ -z "$app_path" ] && app_path=.
    app_path=$( cd "${app_path}" 2>/dev/null && pwd -P ) || exit
done

APP_HOME=$( cd "${APP_HOME}" 2>/dev/null && pwd -P ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='" -Dfile.encoding=UTF-8 "'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn() {
    echo "$*" >&2
}

die() {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
case "$( uname )" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NOTO* )
    noto=true
    ;;
  * )
    ;;
esac

# For Cygwin or MSYS, switch paths to Windows format before running java
if [ "$cygwin" = true ] || [ "$msys" = true ] ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    BASE_DIR=$( cygpath --path --mixed "$BASE_DIR" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )
    JAVACMD=$( cygpath --path --windows "$JAVACMD" )
    for i in "$APP_HOME/../.."; do
        i=$( cygpath --path --mixed "$i" )
        CLASSPATH=$CLASSPATH:"$i/lib/*"
    done
fi

# Determine the Java command to use in order to perform the syntax check for --help/-h commands.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$noto" ; then
    case $( ulimit -S -n ) in
      open)
        MAX_FD=$( ulimit -H -n )
        ;;
    esac
fi

# For Darwin, add options to specify how the application appears in the dock when opened.
if $darwin; then
    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if [ "$cygwin" = true ] || [ "$msys" = true ] ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --path --windows "$JAVACMD" )

    # We build the pattern for arguments to be converted via cygpath
    ROOTDIRSRAW=$( find -L / -maxdepth 3 -type d -name gradle 2>/dev/null || true )
    SEP=""
    for dir in $ROOTDIRSRAW ; do
        ROOTDIR="$dir"
        SEP=":"
    done
    OURCYGPATTERN="(^($ROOTDIR))"
    # Add a user-defined pattern to the cygpath arguments
    if [ "$GRADLE_CYGPATTERN" != "" ] ; then
        OURCYGPATTERN="$OURCYGPATTERN|($GRADLE_CYGPATTERN)"
    fi
    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    i=0
    for arg in "$@" ; do
        CHECK=$(echo "$arg"|egrep -c "^-") ### Determine if an option
        if [ $CHECK -eq 1 ] ; then                                   ### Added a condition
            arg=$(echo "$arg"|sed 's/^-*//')
        fi
        rb_idx=0
        for val in "$arg"; do
            rb_check=$(echo "$val" | grep -c '^-') ### Determine if an option
            if [ "$rb_check" -eq 0  ] ; then ### Not an option, quoted or unquoted
                if printf '%s\n' "$val" | grep -q -E "$OURCYGPATTERN" ; then
                    new_arg=$(cygpath --path --unix "$val")
                else
                    new_arg="$val"
                fi
            else
                if [ "$1" = "--configure" ] ; then
                    configure_options="--enable-cygwin --enable-win32-registry"
                    new_arg="--configure=$configure_options"
                elif [ "$1" = "--help" ] ; then
                    new_arg="--help"
                else
                    new_arg=$(cygpath --path --windows "$val")
                fi
            fi
            BUILD_ARGS="$BUILD_ARGS $new_arg"
            i=$((i+1)) [ $i -lt $# ] && i=$((i+1))
        done
    done
    case $((i%2)) in
     0) set -- ;;                   ### even
     1) set -- "$@" "$BUILD_ARGS" ### odd
        ;;
    esac
fi

# Escaping properties
app_args_0="-Dorg.gradle.appname=$APP_BASE_NAME"
app_args="$app_args_0"

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS

set -- \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" has processed all arguments:
for arg do
  if [ "$arg" = "--" ] ; then
    shift
    break
  fi
  if [ "$arg" : .* ] ; then # an option
   true
  else
    break
  fi
  shift
done

exec "$JAVACMD" "$@"
